resources:
- rhai-code-demo-deploy.yaml
- console.yaml

patches:
  - patch: |-
      - op: add
        path: "/spec/plugins"
        value:
          - rhai-code-demo-plugin
    target:
      group: operator.openshift.io
      kind: Console
      version: v1
      name: cluster
